apiVersion: v1
kind: Service
metadata:
  name: svc-warehouse-service
  namespace: warehouse-service-ns
spec:
  selector:
    app: warehouse-service
  ports:
    - port: 9091
      targetPort: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: warehouse-service
  namespace: warehouse-service-ns
  labels:
    app: warehouse-service
spec:
  replicas: 1
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: warehouse-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 33%
  template:
    metadata:
      labels:
        name: warehouse-service
        app: warehouse-service
    spec:
      containers:
        - name: warehouse-service
          image: warehouse-service:latest
          imagePullPolicy: Always
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: production
          ports:
            - name: http
              containerPort: 9091
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
          readinessProbe:
            httpGet:
              path: /warehouse-service/health
              port: 9091
            initialDelaySeconds: 30
            timeoutSeconds: 2
            periodSeconds: 30
            failureThreshold: 2
          livenessProbe:
            httpGet:
              path: /warehouse-service/health
              port: 9091
            initialDelaySeconds: 60
            timeoutSeconds: 2
            periodSeconds: 30
            failureThreshold: 2
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: warehouse-service
  namespace: warehouse-service-ns
spec:
  maxReplicas: 2
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: warehouse-service
  targetCPUUtilizationPercentage: 80